id = "alloy"
name = "Alloy"
version = "0.1.0"
schema_version = 1
authors = ["genthaler"]
description = "Alloy 6 syntax highlighting for Zed."
repository = "https://github.com/genthaler/zed-alloy"
languages = ["languages/alloy"]

[grammars.alloy6]
repository = "https://github.com/genthaler/tree-sitter-alloy6"
rev = "7c6e3150991279eef3ab1df656b73b13d5fa995f"
